[package]
name = "irc-starbot"
description = "An IRC bot for handling message stars"
readme = "README.md"
license = "MIT"
version = "0.1.0"
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>"]

[dependencies]
regex = "0.1"
irc = "0.9"
